name: Update

on:
  push:
  schedule:
    - cron: 0,30 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update
      run: |
        # 央视源
        rm -f CCTV.m3u && wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/global.m3u -O CCTV.m3u
        sed -i -n '/央视/,+1p' CCTV.m3u
        sed -i '1i #EXTM3U' CCTV.m3u
        sed -i '/^\s*$/d' CCTV.m3u
        # 卫视源
        rm -f CNTV.m3u && wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/global.m3u -O CNTV.m3u
        sed -i '/央视/,+1d' CNTV.m3u
        sed -i '/^\s*$/d' CNTV.m3u
        # 成人源
        rm -f Adult.m3u && wget http://adultiptv.net/chs.m3u -O Adult.m3u
        sed -i 's/XXX/成人/' Adult.m3u
        sed -i 's/AdultIPTV.net //g' Adult.m3u
        wget https://raw.githubusercontent.com/YanG-1989/m3u/main/Adult.m3u -O AdultVideo.txt
        sed -i -n '/日本/,+1p' AdultVideo.txt
        sed -i 's/日本/成人/' AdultVideo.txt
        wget https://raw.githubusercontent.com/YanG-1989/m3u/main/XX.m3u -O AdultLive.txt
        sed -i -n '/直播/,+1p' AdultLive.txt
        sed -i 's/直播/成人/' AdultLive.txt
        echo'' >> Adult.m3u && cat AdultVideo.txt >> Adult.m3u
        cat AdultLive.txt >> Adult.m3u
        rm -f AdultVideo.txt
         rm -f AdultLive.txt
        sed -i '/^\s*$/d' Adult.m3u
        # 整合源
        rm -f IPTV.m3u && touch IPTV.m3u
        cat CCTV.m3u >> IPTV.m3u
        cat CNTV.m3u >> IPTV.m3u
        cat Adult.m3u >> IPTV.m3u
        sed -i '/#EXTM3U/d' IPTV.m3u
        sed -i '1i #EXTM3U' IPTV.m3u
        sed -i '/^\s*$/d' IPTV.m3u
        # 节目源
        rm -f EPG.xml && wget http://epg.51zmt.top:8000/e.xml -O EPG.xml
        # 重置库并上传
        echo `date +"%Y-%m-%d %H:%M:%S"` Finish > README.md
        git config --global user.name atsushi444
        git config --global user.email iori444430@gmail.com
        git checkout --orphan latest_branch
        git add -A
        git commit -am "Update"
        git branch -D main
        git branch -m main
        git push -f origin main
